import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./_components/NavBar";
import container from "./_components/Container";



export const metadata = {
  title: "ORI-IRE",
  description: "Generated by Fawaz Adewuyi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" md:flex md:justify-center border"
        
        >
          <Navbar />
        
        {children}
      </body>
    </html>
  );
}
