import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./_components/NavBar";
import Footer from "./_components/Footer";



const proxNovar = localFont({
  src: "./fonts/DMSans-Regular-BF64376d323f095.ttf",
  variable: "--font-proxnovar",
  weight: "100 300 400 600 900",
});
const proxNovabold = localFont({
  src: "./fonts/Proxima Nova Bold.otf",
  variable: "--font-proxnovabold",
  weight: "900",
});
const proxNovablack = localFont({
  src: "./fonts/Proxima Nova Black.otf",
  variable: "--font-proxnovablack",
  weight: "100 400 600 900",
});

const domaineDisplay = localFont({
  src: "./fonts/PlusJakartaSans-Regular.ttf",
  variable: "--font-domainer",
  weight: "100 400 500 600 700 900",
});



export const metadata = {
  title: "ORI-IRE",
  description: "Generated by Fawaz Adewuyi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ `md:flex md:justify-center md:items-center md:flex-col border ${domaineDisplay.variable} ${proxNovar.variable}`}
        
      >
          
          <Navbar />

        
        {children}
        <Footer />
      </body>
    </html>
  );
}
